[package]
name = "aeneas_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_extension"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]

[dependencies]
ndarray = "0.15"

